main: org.dragonet.bukkit.ultimateroles.UltimateRolesPlugin
version: 1.2
name: UltimateRoles
author: DefinitlyEvil
depend: ["LuckPerms"]
commands:
  myperks:
    description: list of your perks
  clearperms:
    description: DO NOT USE IT, it will make you a RETARD
