#  ________                           __________ .__
#  \______ \    ____  _______ ______  \______   \|  |   __ __   ______
#   |    |  \ _/ __ \ \_  __ \\____ \  |     ___/|  |  |  |  \ /  ___/
#   |    `   \\  ___/  |  | \/|  |_> > |    |    |  |__|  |  / \___ \
#  /_______  / \___  > |__|   |   __/  |____|    |____/|____/ /____  >
#          \/      \/         |__|                                 \/

# The ULTIMATE TROLLING plugin!

